[project]
name = "interagentv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.1.0",
    "openai>=1.109.1",
    "opencv-python>=4.12.0.88",
    "pyyaml>=6.0.3",
    "scikit-image>=0.25.2",
]
